### ISSUE TITLE
PROBLÈME URGENT

### ISSUE THREAD

**Issue by felix1737397** [Giant-T/HttPauvre#2]
Bonjour, quand j'effectue la commande cargo run --release 

un message d'erreur s'affiche indiquant **"'cargo' is not recognized as an internal or external command, operable program or batch file."** 

Merci de régler le problème au plus vite. 

Bonne journée,
Félix

**Comment by Giant-T** [comment]
Faut que t'installe cargo

**Comment by felix1737397** [comment]
Merci de faire l'installation et m'indiquer lorsque ce sera fait. Merci!

**Comment by elliotGaulin** [comment]
T'es un peu cave M Giant.

**Comment by snakeeyes1023** [comment]
J'ai le même problème... Est-ce qu'il y a du dévellopement sur la cause ou une piste de solution ?????

Au plaisir!

**Comment by Giant-T** [comment]
😢

**Comment by felix1737397** [comment]
Je vois que d'autres utilisateurs sont de mon avis. Bien vouloir remédier à la situation rapidement. 

Bien à vous,
Félix
